### ISSUE TITLE
Hello, are you also doing an update to the nodeJS like your sister project?

### ISSUE THREAD

**Issue by Slippy2k** [johndimi/cdcrush#2]
Hello, are you also doing an update to the nodeJS like your sister project v1.5?

**Comment by john32b** [comment]
Hi! 

Yes eventually. Updating the nodejs version is on my todo list for a while now.

**Comment by Slippy2k** [comment]
That's great, I'm looking forward to the new version with the new Formats !

**Comment by john32b** [comment]
a0dbabe3b2cf53c6870d32ae8b7d4a4f6ff1f75f

No standalone build yet, but published it to NPM
